### PR TITLE
Resolve issue 39

### PR DESCRIPTION
**Pull request by yy665**
@dz333 

Changed `e.to.mergeStmts(nstmts, false)` to allow recv stmt gets prepended.

### CODE REVIEW

**Comment by dz333** [comment]
Great! Can you add a test to the `src/test/tests/branchesCheck` folder with the example from the issue (or something similar)?
See the other tests in that directory for how to specify solution files (that go in `src/test/tests/branchesCheck/solutions`) and memory files to specify the memory initial state for simulation (`src/test/tests/branchesCheck/memInputs`).

Once you add the test file I can also help make sure it's running properly.

**Comment by yy665** [comment]
> Great! Can you add a test to the `src/test/tests/branchesCheck` folder with the example from the issue (or something similar)? See the other tests in that directory for how to specify solution files (that go in `src/test/tests/branchesCheck/solutions`) and memory files to specify the memory initial state for simulation (`src/test/tests/branchesCheck/memInputs`).
> 
> Once you add the test file I can also help make sure it's running properly.

Thanks for the feedback.

I have added some test files. Not sure if these tests are good. I tried to run the tests locally but there are some issues with my local bsc simulator.

**Review by dz333 — COMMENTED** [review]
Looks good! The only issue is that your solution file for the simulation has the wrong number of spaces (that's why the test is failing). The simulator right aligns numbers based on the number of bits in their type.

**Comment by dz333** [comment]
I've merged it into `main` with a fix for the solution file

**Comment by yy665** [comment]
Thanks! @dz333

**Pull request merged**
